"""added avatar and removed unwanted columns form bots

Revision ID: 000f115274a6
Revises: 581ced9c902d
Create Date: 2025-05-11 02:09:55.182036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000f115274a6'
down_revision: Union[str, None] = '581ced9c902d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('avatar', sa.String(), nullable=True))
    op.drop_column('bots', 'type')
    op.drop_column('bots', 'price')
    op.drop_column('bots', 'visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('visibility', postgresql.ENUM('PUBLIC', 'PRIVATE', name='botvisibility'), autoincrement=False, nullable=True))
    op.add_column('bots', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bots', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bots', 'avatar')
    # ### end Alembic commands ###
