"""added ability for users to buy bots

Revision ID: 11e69cb43bd3
Revises: ec35441c7dab
Create Date: 2025-07-23 22:04:34.959433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e69cb43bd3'
down_revision: Union[str, None] = 'ec35441c7dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premium_bots_access',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premium_bots_access')
    # ### end Alembic commands ###
