"""changed the sender field

Revision ID: 4db000a80063
Revises: 4d9c875cfffd
Create Date: 2025-06-20 01:58:47.448552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4db000a80063'
down_revision: Union[str, None] = '4d9c875cfffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender',
               existing_type=postgresql.ENUM('USER', 'BOT', name='messagesender'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender',
               existing_type=sa.String(),
               type_=postgresql.ENUM('USER', 'BOT', name='messagesender'),
               existing_nullable=False)
    # ### end Alembic commands ###
