"""Added type field to the bot model

Revision ID: 6270a3991fb7
Revises: b9b6caaf2fbc
Create Date: 2025-02-01 19:50:30.674294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6270a3991fb7'
down_revision: Union[str, None] = 'b9b6caaf2fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('type', sa.String(), nullable=True))
    op.drop_index('ix_transactions_bot_id', table_name='transactions')
    op.create_foreign_key(None, 'transactions', 'bots', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_index('ix_transactions_bot_id', 'transactions', ['bot_id'], unique=False)
    op.drop_column('bots', 'type')
    # ### end Alembic commands ###
