"""Remove bot relationship from transaction

Revision ID: b910e4d62724
Revises: df08206d575a
Create Date: 2025-07-20 00:18:18.672091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b910e4d62724'
down_revision: Union[str, None] = 'df08206d575a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_bot_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'bot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('bot_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('transactions_bot_id_fkey', 'transactions', 'bots', ['bot_id'], ['id'])
    # ### end Alembic commands ###
