"""added premium field to bot model

Revision ID: ec35441c7dab
Revises: cfaf027d2823
Create Date: 2025-07-23 21:55:02.651276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec35441c7dab"
down_revision: Union[str, None] = "cfaf027d2823"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bots",
        sa.Column("premium", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bots", "premium")
    # ### end Alembic commands ###
